git clone https://github.com/vim-scripts/L9.git
git clone https://github.com/tomtom/tlib_vim.git
git clone https://github.com/scrooloose/nerdtree.git
git clone https://github.com/scrooloose/nerdtree.git
git clone https://github.com/majutsushi/tagbar.git
git clone https://github.com/elrvandew/supertab.git
git clone https://github.com/airblade/vim-gitgutter.git
git clone https://github.com/garbas/vim-snipmate.git
git clone https://github.com/honza/vim-snippets.git
git clone https://github.com/kchmck/vim-coffee-script.git
git clone https://github.com/Shougo/neocomplete.git
git clone https://github.com/w0rp/ale.git
git clone https://github.com/kien/ctrlp.vim.git
git clone https://github.com/tpope/vim-fugitive.git
git clone https://github.com/tpope/vim-rails.git
git clone https://github.com/vim-ruby/vim-ruby.git
git clone https://github.com/vim-airline/vim-airline.git
git clone https://github.com/vim-airline/vim-airline-themes.git
git clone https://github.com/godlygeek/tabular.git
git clone https://github.com/plasticboy/vim-markdown.git
git clone https://github.com/bronson/vim-trailing-whitespace.git
git clone https://github.com/junegunn/vim-easy-aling.git
